### ISSUE TITLE
Google Pixel bug

### ISSUE THREAD

**Issue by zoblue** [googlecreativelab/tunnelvision#1]
The app is not recording video, only audio. When I try to record a new tunnel vision video it seems to work fine but on playback there is only a still image with the audio. It also saves to the phone a still image with audio, not video. I have a Google Pixel with Android 7.1.

**Comment by hapticdata** [comment]
Thank you for reporting this bug. Sounds like it might be an issue with our [shadercam](https://github.com/googlecreativelab/shadercam) library. I hope to get my hands on a Pixel and look into this soon.

**Comment by jeetdholakia** [comment]
I can confirm that this is happening not just on my pixel (8.0) but also samsung s7 edge (7.1.1), it was a problem that did not happen before, now it's there for all shadercam apps...

**Comment by tcmeggs** [comment]
This is also happening to me on the Pixel 2.
