### ISSUE TITLE
Doesn't resolve dependency 'com.androidexperiments:shadercam:1.0.1'

### ISSUE THREAD

**Issue by joker-b** [googlecreativelab/tunnelvision#2]
I really enjoyed messing with TunnelVision on Nexus 6 and now am trying to dig a little deeper.

Has the dependency code been removed recently?

Instead I cloned the shadercam module and imported it into tunnelvision while removing the androidexperiments dependency -- worked fine, but thought it worthwhile to mention that this repo might not run for everyone "out of the box."

**Comment by hapticdata** [comment]
thanks for bringing this to my attention, I hope to look into this soon

**Comment by jeetdholakia** [comment]
Same problem here...
